/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 land-v1.glb --transform --types
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
  };
  materials: {
    ["Land Color"]: THREE.MeshStandardMaterial;
  };
};

const Land = (props: JSX.IntrinsicElements["mesh"]) => {
  const { nodes, materials } = useGLTF("/models/land.glb") as GLTFResult;
  return (
    <mesh
      {...props}
      geometry={nodes.Plane.geometry}
      material={materials["Land Color"]}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI, 0.03, -Math.PI]}
      scale={30}
    />
  );
};

useGLTF.preload("/models/land.glb");

export { Land };
